///
/// @copyright 2015 Adam Meily <meily.adam@gmail.com>
///

///
/// Do not edit this file. The site configuration file is located in
/// conf/app-config.js.
///



var _ = require('underscore');
var util = require('util');


function MrIssueConfig(data) {
  var self = this;

  this.redmine = data.redmine;
  this.projects = [];

  var globalActions = data.globalActions || {};

  _.each(data.projects, function(project) {
    for(var actionName in globalActions) {
      project.actions[actionName] = _.defaults({}, project.actions[actionName], globalActions[actionName]);
    }

    self.projects.push(project);
  });
}

MrIssueConfig.prototype.getUserLookups = function() {
  var lookups = [];

  _.each(this.projects, function(project) {
    //_.each(project.actions, function(actionName) {
    for(var actionName in project.actions) {
      var actions = project.actions[actionName];
      if(actions.assignedTo) {
        lookups.push(actions.assignedTo);
      }
    }
  });

  return _.uniq(lookups);
};

MrIssueConfig.prototype.getIssueStatusLookups = function() {
  var lookups = [];

  _.each(this.projects, function(project) {
    for(var actionName in project.actions) {
      var actions = project.actions[actionName];
      if(actions.status) {
        lookups.push(actions.status);
      }
    }
  });

  return _.uniq(lookups);
}

MrIssueConfig.prototype.getProjectConfig = function(url) {
  var name = url.substring(1);
  for(var i in this.projects) {
    var proj = this.projects[i];
    if(proj.name == name) {
      return proj;
    }
  }
  return null;
};

module.exports = new MrIssueConfig(require('./conf/app-config'));
